/**
 * the lake is the largest body of water, generated by two opposite side triangle
 * e.g
 * 0000000011111111100
 * 0000000111111111100
 * 0000001111111111000
 * 0000011111111110000
 * 0000111111111100000
 *
 * @ x    the x coordinate of the upper left corner
 * @ y    the y coordinate of the upper left corner
 * @ size the side length of the water body
 */

public class CreateLake extends BasicDrawings implements Constructions {


    private final int size;

    public CreateLake(int x, int y, int size) {
        super.x = x;
        super.y = y;
        this.size = size;
    }

    @Override
    public boolean sizeIsValid() {
        return size > 2;
    }

    @Override
    public boolean coordinateIsValid() {
        if (
                !validCoordinate(x, y) ||
                        !validCoordinate(x, y + 2 * size) ||
                        !validCoordinate(x + size, y + size) ||
                        !validCoordinate(x + size, y - size)

        ) {
            return false;
        } else {
            return true;
        }

    }

    @Override
    public void construct() {
        if (sizeIsValid() && coordinateIsValid()) {
            //create the lake
            drawTriangle(x, y, size, 1, "up");
            drawTriangle(x + size, y + size, size, 1, "down");

            //the lake is full of water, it is automatically filled
            fill(x + 2, y, 1);
            fill(x + size - 2, y + size, 1);
        } else {

            throw new RuntimeException("The construction of lake fails");

        }

    }
}
